### ISSUE TITLE
Support conditionally setting arguments to a command

### ISSUE THREAD

**Issue by huonw** [a-scie/jump#130]
In https://github.com/pantsbuild/scie-pants/issues/249, we encounter a circumstance where a `command` has an `arg` that needs to be conditionally set: a binding computes an env var that is sometimes set to `--python-repos-find-links=...` and sometime empty. If the env var is empty, it'd be better for the command to not receive an argument: invoking `pants "" ...` causes issues with pants specifically, and in general passing a spurious empty string is likely to cause problems for any program.

It'd be handy to be able to (optionally) make an argument conditional, so that these sort of "maybe set an argument" uses cases are easier to handle. 

AFAICT, this isn't currently possible with scie-jump: there's a reified argument for every argument in the manifest, and string like `"{scie.bindings.configure:PANTS_SHA_FIND_LINKS}"` just becomes an empty string.

https://github.com/a-scie/jump/blob/1403e1f26d89bf67d7df3d630d9931397213bf11/jump/src/context.rs#L270-L274

https://github.com/a-scie/jump/blob/1403e1f26d89bf67d7df3d630d9931397213bf11/jump/src/context.rs#L576-L581

Suppose there's a manifest like the following, we'd like to be able to annotate the `ARGUMENT` arg to disappear completely in some cases (particularly when `ARGUMENT` is empty, but a more general mechanism would be okay too):

```json
...
"commands": {
  "": {
    "exe": ".../executable"
    "args": ["{scie.bindings.some_binding:ARGUMENT}"]
  }
}
...
```

In shell terms:

```shell
ARGUMENT=""

.../executable "$ARGUMENT" # current behaviour: passing a "" argument

.../executable $ARGUMENT # requested behaviour: no argument at all
```

Workaround that we'll likely use in https://github.com/pantsbuild/scie-pants/issues/250: instead of setting the env var to nothing, set it to a "no-op" argument, so that we're never passing an empty arg to the executable.

(This may apply to arguments in bindings in addition to commands?)

**Comment by jsirois** [comment]
@huonw as I noted here: https://github.com/pantsbuild/scie-pants/issues/249#issuecomment-1693521867, scie-jump doesn't support dynamic commands, the lift manifest is static save for interpolation. None the less, commands can be selected dynamically by using recursive dispatch. This is what scie-pants already does to handle the debug case. I'd really like to keep scie-jump simple as per the general thrust outlined here: https://github.com/a-scie/jump/blob/main/CONTRIBUTING.md#guiding-principles

Does the recursive dynamic dispatch of commands that scie-pants already does suffice for you @huonw?

**Comment by huonw** [comment]
Yep, happy to call that sufficient for this. I assume you aware of the combinatorial explosion (if one has 2 args that might need to disappear independently, I think one will need 4 `commmand`s for the different combinations of present vs not; 3 args => 8 `command`s, etc?), but, as I said, happy to call this one answered.

**Comment by jsirois** [comment]
Yeah, I'm aware Pants would need to go from 2 to 4 commands the way it's currently doing things. My initial thought was to not do things this way (not have the existing configuration / install handle PEX installs), but to have Pants release an unpacked scie (PEX + manifest) where each release of Pants could have arbitrarily complex bespoke to the version complexity (see: https://github.com/a-scie/jump/issues/10).

All that said, isn't scie-pants / Pants engaged in hoisting and petards here? IIUC one can say `"--python-repos-find-links=[]"` to indicate to Pants a base set of 0 find links repos (or via env var), or `"--python-repos-find-links=foo` to append one, etc? I.E. I think it's the case that scie-pants could have solved this totally in house in a clean way.

**Comment by jsirois** [comment]
I noted what seems to me to be the root bug here: https://github.com/pantsbuild/scie-pants/pull/226#discussion_r1306167997

**Comment by huonw** [comment]
Yeah, in this case, there's an "obvious" no-op value, so that's the fix we went for in https://github.com/pantsbuild/scie-pants/pull/250
