### ISSUE TITLE
.env loading fails partially and silently on invalid files

### ISSUE THREAD

**Issue by huonw** [a-scie/jump#163]
The current use of `dotenvy` for applying `.env` files results in:

1. errors being silently ignored (e.g. lines that can't be parsed), which is very confusing for users of a scie-jump packaged binary, like scie-pants
2. (potentially not a problem) a `.env` file being partially applied, where all lines before the first error are applied, and all lines (even valid ones) after the first error are ignored (due to `dotenvy`'s immediate bail out on error https://github.com/allan2/dotenvy/blob/08e35eea693ca12c4038a226bae2e3144445ba69/dotenv/src/iter.rs#L33)
 
https://github.com/a-scie/jump/blob/f44ca18f9c6e8a02f8fab84f6e22c8887b5a3267/jump/src/lib.rs#L181-L186

This was observed in practice in https://github.com/pantsbuild/scie-pants/issues/307.

**Comment by jsirois** [comment]
Aha - I'm dumb: https://docs.rs/dotenvy/0.15.7/dotenvy/fn.from_filename.html

**Comment by jsirois** [comment]
I'm dumber - the returned error type is rich enough to distinguish.

**Comment by jsirois** [comment]
Alright, the fix is now released in 0.13.2: https://github.com/a-scie/jump/releases/tag/v0.13.2
